### ISSUE TITLE
Wireframes Security Sections

### ISSUE THREAD

**Issue by cassina** [devf-dojo/dojo-front#2]
- [ ] Develop the login page.
- [ ] Develop index.

Are there other sections **needed for the mvp** that we should design?

**Comment by ghost** [comment]
- [ ] Create the full landing page with the same look & feel from [Dojo page](https://dojo.devf.mx/)

**Comment by cassina** [comment]
Inspiration for the login page.

![screen shot 2017-07-31 at 21 11 14](https://user-images.githubusercontent.com/9815363/28806373-454bdc3a-7635-11e7-8445-3294fdc20afa.png)

**Comment by fabo57** [comment]
On login successful ridirec to index.

**Comment by cassina** [comment]
Se está trabajando la implementación de estas secciones en los issues #23 #15 #14 #16
